#
# The scope of support conforms to the nodejs official.
# https://github.com/nodejs/Release/blob/master/README.md
#
# Version of node managed by DockerHub.
# https://hub.docker.com/_/node/
#
language: node_js
node_js:
  - "15"
  - "14"
  - "12"
  - "10"
after_script:
  - yarn coveralls
